### ISSUE TITLE
Live site country search not working

### ISSUE THREAD

**Issue by imhayatunnabi** [ChamuMutezva/rest-countries-api-javascript#2]
Hello fellow,
I have noticed some issue in your live site that you search option is not working or not responding to the api. I would like to request you to solve the issue. 
![image](https://user-images.githubusercontent.com/44812376/155325161-da982053-b890-44f5-bd05-91c64b5ac8d5.png)

**Comment by ChamuMutezva** [comment]
Hi. Thanks for highlighting the issue, I will look into it soon. The API that I was using has been changed, I will have to look for an alternative

**Comment by imhayatunnabi** [comment]
https://restcountries.com/v3.1/all 

# use this instread

**Comment by ChamuMutezva** [comment]
Thanks, so much

**Comment by ChamuMutezva** [comment]
Had some today to fix that issue. You can check again
